<?php
/**
* @author Awd Team
* @copyright Copyright (c) 2021 Awd (https://www.advancedwebsitedesign.co.uk)
* @package Awd_Base
*/
?>
<?php
/**
 * @var \Awd\Base\Block\Import $block
 */
?>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/alert',
            'prototype'
        ], function($) {
            //<![CDATA[
            var entity = $('#entity');
            entity.hide();
            entity.closest('fieldset').find('label.label.admin__field-label').css('visibility','hidden');
            $(entity).val('<?= $block->escapeHtml($block->getImportEntity()) ?>');
            varienImport.handleEntityTypeSelector();
            //]]>
        }
    );
</script>
