<?php
/**
* @author Awd Team
* @copyright Copyright (c) 2021 Awd (https://www.advancedwebsitedesign.co.uk)
* @package Awd_Base
*/
?>
<?php
/** @var \Awd\Base\Block\Adminhtml\Messages $block */
$messages = $block->getMessages();
?>
<?php if (!empty($messages)): ?>
    <?php foreach ($messages as $message): ?>
        <div class="messages ambase-unsubscribe">
            <div class="message message-success success">
                <div data-ui-id="messages-message-success"><?= /* @noEscape */ $message;?></div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
